### ISSUE TITLE
Only load my own attributes

### ISSUE THREAD

**Issue by ruudk** [olvlvl/php-attribute-collector#3]
It seems that the plugin is scanning all files, including `vendor`.

I'd rather have it only spend time on my `src` directory. Would it be possible to configure what it scans?

**Comment by olvlvl** [comment]
The plugin scans every class Composer is configured to autoload. I guess it could check for an extra section in `composer.json` to ignore some paths. Let's say it looked like that, how would you use it?

```json
{
  "extras" {
    "attribute-collector": {
      "ignore-paths": []
    }
  }
}
```

**Comment by beberlei** [comment]
Could one solution be to scan only src by default and then each package that wants to be scanned defines this in their extra section? This way all packages that use the auto discovery in a way can register themselves to "provide" or "use" these attributes.

**Comment by olvlvl** [comment]
Hi, could you try this branch? https://github.com/olvlvl/composer-attribute-collector/pull/5
